In [1]:
import numpy as np

In [2]:
a = [6,7,8,9,10]
b = np.array(a)
b

array([ 6,  7,  8,  9, 10])

In [3]:
type(b)

numpy.ndarray

In [4]:
a = []
size = int(input("enter the size"))
for i in range(size):
    val = int(input("enter the number"))
    a.append(val)

print(a)
b = np.array(a)
b

enter the size 4
enter the number 24
enter the number 68
enter the number 69
enter the number 70


[24, 68, 69, 70]


array([24, 68, 69, 70])

In [5]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
print("total dimesnsions", b.ndim)
print("shape of an array",b.shape)
print("total elements",b.size)

total dimesnsions 2
shape of an array (3, 3)
total elements 9


In [7]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [9]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
b.ndim

2

In [11]:
a.ndim

1

In [12]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [13]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
b = np.eye(3,4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [16]:
a = np.random.randint(1,10,3)
a

array([5, 4, 5])

In [17]:
a = np.random.rand(5)
a

array([0.84015798, 0.83501218, 0.01052807, 0.48167143, 0.09844833])

In [18]:
a = np.random.randint(1,50,12)
a

array([23, 44, 27, 21, 41, 15, 37,  8,  7, 20, 38, 15])

In [19]:
a.shape

(12,)

In [20]:
a.reshape(6,2)
a

array([23, 44, 27, 21, 41, 15, 37,  8,  7, 20, 38, 15])

In [21]:
a.reshape(3,4)
a

array([23, 44, 27, 21, 41, 15, 37,  8,  7, 20, 38, 15])

In [22]:
a = a.reshape(3,4)
a

array([[23, 44, 27, 21],
       [41, 15, 37,  8],
       [ 7, 20, 38, 15]])

In [23]:
a = a.reshape(4,3)
a

array([[23, 44, 27],
       [21, 41, 15],
       [37,  8,  7],
       [20, 38, 15]])

In [24]:
a = a.reshape(12,1) 
a

array([[23],
       [44],
       [27],
       [21],
       [41],
       [15],
       [37],
       [ 8],
       [ 7],
       [20],
       [38],
       [15]])

In [25]:
a = a.reshape(-1 , 4) 
a

array([[23, 44, 27, 21],
       [41, 15, 37,  8],
       [ 7, 20, 38, 15]])

In [26]:
np.random.seed(555) 
a = np.random.randint(1,100 , 10) 
a

array([27, 47, 34, 69, 39, 23, 54, 97, 85, 23])

In [27]:
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6] 
b[:] = 0 
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [28]:
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6].copy() 
b[:] = 0 
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [29]:
a = np.arange(1,16) 
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [31]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [32]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [33]:
a = np.arange(1,5) 
print(a)
print(a*2)

[1 2 3 4]
[2 4 6 8]


In [34]:
a + 2


array([3, 4, 5, 6])

In [35]:
a**2

array([ 1,  4,  9, 16])

In [36]:
a  = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [37]:
b = np.array([5,6,7,8]).reshape(2,2) 
b

array([[5, 6],
       [7, 8]])

In [38]:
a + b

array([[ 6,  8],
       [10, 12]])

In [39]:
a - b

array([[-4, -4],
       [-4, -4]])

In [40]:
b/a

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [41]:
a*b

array([[ 5, 12],
       [21, 32]])

In [42]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [43]:
a = np.array([10,20,30,40,50]) 
np.min(a) 

10

In [44]:
np.max(a)

50

In [45]:
np.argmin(a)

0

In [46]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [47]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

In [48]:
a = np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [49]:
np.random.seed(122) 
a = np.random.randint(1,21,9).reshape(3,3) 
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [50]:
np.sum(a)

116

In [51]:
np.sum(a , axis = 1) 

array([40, 46, 30])

In [52]:
np.min(a)

3

In [53]:
np.max(a)

17

In [54]:
np.cumsum(a)

array([ 16,  27,  40,  57,  70,  86,  89, 105, 116])

In [55]:
a

array([[16, 11, 13],
       [17, 13, 16],
       [ 3, 16, 11]])

In [56]:
a = np.array([10,20,30,40,10,20,50]) 
np.unique(a , return_index  = True , return_counts = True)

(array([10, 20, 30, 40, 50]),
 array([0, 1, 2, 3, 6], dtype=int64),
 array([2, 2, 1, 1, 1], dtype=int64))

In [57]:
b

array([[5, 6],
       [7, 8]])

In [59]:
a = np.array([1,2,3,4]) 
b = np.array([5,6,7,8]) 
c = np.array([9,10,11,12])
a

array([1, 2, 3, 4])

In [60]:
b

array([5, 6, 7, 8])

In [61]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [62]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
a = [6,7,8,9,10]
b = np.array(a)
b

array([ 6,  7,  8,  9, 10])

In [66]:
random_integers = np.random.randint(0, 100, 10)
print(random_integers)

[21 31 41 70 78 35 95 51 19 13]


In [67]:
array_10_to_20 = np.arange(10, 21)
array_10_to_20

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [68]:
array_of_fives = np.full(10, 5)
array_of_fives


array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [69]:
one_d_array = np.arange(1, 10)

matrix_3x3 = one_d_array.reshape(3, 3)
print(matrix_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [71]:
array_2 = np.random.rand(3, 3)
print(array_2)

[[0.69706053 0.90947522 0.32969608]
 [0.18556863 0.23302723 0.83350707]
 [0.01058107 0.25603062 0.17080412]]


In [75]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

h_concat = np.hstack((arr1, arr2))

h_concat_alt = np.concatenate((arr1, arr2), axis=1)

print(h_concat)

[[1 2 5 6]
 [3 4 7 8]]
